Add Forms for adding a post, adding a comment and a like button
alexiscyber14/ruby_on_rails_blog_app pull request #8
Opened 2023-06-20 22:10 UTC by alexiscyber14

Requirements:

Create a method called current_user in your ApplicationController to make current user data available to all controllers.
It will return the first user from the database.
Don't worry about proper authentication at this time. You will add it in the upcoming projects.
Create forms to perform the following functions:
Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
Allow Users to add likes to Posts.

2023-06-20 22:51 UTC, Felix45 requested changes
Hi @alexiscyber14 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] Blog forms work as expected :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:   

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 22:51 UTC, Felix45 commented on app/views/posts/show.html.erb
>  <p class="said-two"> &#128394;&#65039 <%= @post.text %> Styling is nice to have but focus on making sure everything functions firstStyling is nice to have but focus on making sure everything function
- [ Required ] I think it would be better if the only text that is displayed on the posts `show` page is from the `post.text` that has been clicked just as is in the project wireframe. Currently, there is a static text that is displayed for any post that is clicked. Please see the screenshot below and rectify this.

## Example code
```ruby
  <p class="said-two">  <%= @post.text %></p>
```

## Screenshot
![Screenshot from 2023-06-21 01-33-07](https://github.com/alexiscyber14/ruby_on_rails_blog_app/assets/16392046/a03e8c97-d6bc-4b6b-bd96-b3ac08dd6fb6)

2023-06-20 22:51 UTC, Felix45 commented on app/views/users/show.html.erb
- [ Required ] I think it would be better if the only text that is displayed on the users `show` page is from the `post.text` that has been clicked just as is in the project wireframe. Currently, there is a static text that is displayed for any user that is clicked. Please see the screenshot below and rectify this.

## Example code
```ruby
  <p class="said-two">  <%= @post.text %></p>
```

## Screenshot
![Screenshot from 2023-06-21 01-42-00](https://github.com/alexiscyber14/ruby_on_rails_blog_app/assets/16392046/13b3b4b1-aa91-410b-8e74-909fa9c378c8)

2023-06-21 06:49 UTC, alexiscyber14 commented on app/views/posts/show.html.erb
>  <p class="said-two"> &#128394;&#65039 <%= @post.text %> Styling is nice to have but focus on making sure everything functions firstStyling is nice to have but focus on making sure everything function
@Felix45  let me make the changes

2023-06-21 07:38 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 07:45 UTC, merged